from __future__ import annotations

# Datasets
from .dataset_loaders import (
    BaseDatasetLoader,
    CharityReportLoader,
    FCCInvoiceLoader,
    LoaderColumns,
    NDALoader,
    ResourceContractLoader,
    SECS1Loader,
)

# Preprocessing
from .preprocessing import (
    OCRToken,
    OCRBlock,
    Annotation,
    LabeledSpan,
    AlignmentIssue,
    AlignmentResult,
    CanonicalDocument,
    add_token_labels,
    align_annotations_to_bio,
    bio_to_spans,
    annotation_summary,
    build_bio_label_list,
    build_label_maps,
    common_labels,
    document_frequency,
    label_to_key,
    normalize_label_name,
    parse_annotations,
    select_labels_by_doc_frequency,
    bbox_center,
    bbox_iou,
    bbox_union,
    extract_blocks_from_ocr,
    extract_page_sizes,
    extract_text_from_ocr,
    extract_tokens_from_ocr,
    line_group_tokens,
    normalize_bbox,
    parse_json_like,
    read_json_or_gzip,
    token_row_col_buckets,
)

# Serialization
from .serialization import (
    IGNORE_LABEL,
    BaseSerializer,
    SerializedItem,
    PlainTextSerializer,
    PageAwareSerializer,
    BlockAwareSerializer,
    LineAwareSerializer,
    RowColBucketSerializer,
    BBoxTokenSerializer,
    ColumnAwareSerializer,
    XYCutAwareSerializer,
    LMDXCoordSuffixSerializer,
    CompactBBoxTokenSerializer,
    PrecedenceGraphOrderSerializer,
    KeyValueRowPairsSerializer,
    KeyValueAnchorPairsSerializer,
    T5JsonSerializer,
    TOKEN_CLASSIFICATION_SERIALIZERS,
    SEQ2SEQ_SERIALIZERS,
    ALL_SERIALIZERS,
    get_serializer_class,
    rebuild_bio_labels_for_serialized_order,
    collapse_serialized_labels_to_original,
    iter_real_serialized_positions,
    infer_token_block_ids,
)

# Training
from .training import (
    ExperimentConfig,
    ModelSpec,
    DataPipeline,
    ExperimentData,
    TokenizedCorpus,
    ExperimentRunner,
    FocalLossTrainer,
    InMemoryBestModelCallback,
    TrainingState,
    focal_loss_for_token_classification,
    build_arg_parser,
    build_config_from_args,
)

__all__ = [
    # Datasets
    "BaseDatasetLoader",
    "CharityReportLoader",
    "FCCInvoiceLoader",
    "LoaderColumns",
    "NDALoader",
    "ResourceContractLoader",
    "SECS1Loader",
    # Preprocessing - Schema
    "OCRToken",
    "OCRBlock",
    "Annotation",
    "LabeledSpan",
    "AlignmentIssue",
    "AlignmentResult",
    "CanonicalDocument",
    # Preprocessing - Alignment
    "add_token_labels",
    "align_annotations_to_bio",
    "bio_to_spans",
    # Preprocessing - Label utilities
    "annotation_summary",
    "build_bio_label_list",
    "build_label_maps",
    "common_labels",
    "document_frequency",
    "label_to_key",
    "normalize_label_name",
    "parse_annotations",
    "select_labels_by_doc_frequency",
    # Preprocessing - OCR utilities
    "bbox_center",
    "bbox_iou",
    "bbox_union",
    "extract_blocks_from_ocr",
    "extract_page_sizes",
    "extract_text_from_ocr",
    "extract_tokens_from_ocr",
    "line_group_tokens",
    "normalize_bbox",
    "parse_json_like",
    "read_json_or_gzip",
    "token_row_col_buckets",
    # Serialization
    "IGNORE_LABEL",
    "BaseSerializer",
    "SerializedItem",
    "PlainTextSerializer",
    "PageAwareSerializer",
    "BlockAwareSerializer",
    "LineAwareSerializer",
    "RowColBucketSerializer",
    "BBoxTokenSerializer",
    "ColumnAwareSerializer",
    "XYCutAwareSerializer",
    "LMDXCoordSuffixSerializer",
    "CompactBBoxTokenSerializer",
    "PrecedenceGraphOrderSerializer",
    "KeyValueRowPairsSerializer",
    "KeyValueAnchorPairsSerializer",
    "T5JsonSerializer",
    "TOKEN_CLASSIFICATION_SERIALIZERS",
    "SEQ2SEQ_SERIALIZERS",
    "ALL_SERIALIZERS",
    "get_serializer_class",
    "rebuild_bio_labels_for_serialized_order",
    "collapse_serialized_labels_to_original",
    "iter_real_serialized_positions",
    "infer_token_block_ids",
    # Training
]
